spring:
  application:
    name: JavaChip

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: never

  mvc:
    hiddenmethod:
      filter:
        enabled: true